### ISSUE TITLE
loaders

### ISSUE THREAD

**Issue by yubathom** [SPURB/participe-elementos-interface#1]
Criar svgs animados - [exemplo](https://codepen.io/yubathom/pen/PxPWYy):
- pré-loader (primeiro carregamento)
- loader em main em todas as trocas de rota
- fetch das contribuições (hero)
- fetch do comentários
	- enviando
	- sucesso 
	- fracasso

**Comment by flavinhalopes** [comment]
#### Estudo dos loaders: 
\\SPURBSP01\Comunicacao\participe\icones\estudo_preloaders.ai

**Comment by flavinhalopes** [comment]
#### Estudo animação chatbox :+1:
https://codepen.io/flavinhalopes/pen/KrNWdJ
![image](https://user-images.githubusercontent.com/39636035/48366247-5f1bb600-e694-11e8-9aea-792ff6633945.png)

**Comment by flavinhalopes** [comment]
**Animação pre-loader página**
https://codepen.io/flavinhalopes/pen/YRNaMw
![sem-titulo-1](https://user-images.githubusercontent.com/39636035/48429681-c4cf7700-e754-11e8-835b-5f376a499cc8.png)

**Comment by yubathom** [comment]
Resolvido em https://github.com/SPURB/participe/commit/741782752d444338b9d995a7f54dde939146430f
